/*
 * ConfigUI.java
 *
 * Created on December 4, 2007, 2:11 PM
 */

package powerreader;

import util.TextObject3d;

/**
 *
 * @author  Christopher Leung
 */
public class ConfigUI extends javax.swing.JFrame {
    
    /** Creates new form ConfigUI */
    public ConfigUI() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        m_combo_dictionaryLookup = new javax.swing.JComboBox();
        m_combo_imageLookup = new javax.swing.JComboBox();
        m_combo_fontFace = new javax.swing.JComboBox();
        m_combo_voicePersonality = new javax.swing.JComboBox();
        m_combo_leftClick = new javax.swing.JComboBox();
        m_combo_middleClick = new javax.swing.JComboBox();
        m_combo_rightClick = new javax.swing.JComboBox();
        m_okButton = new javax.swing.JButton();
        m_cancelButton = new javax.swing.JButton();
        m_checkBox_mouseWheel = new javax.swing.JCheckBox();
        m_label_dictionarySource = new javax.swing.JLabel();
        m_label_imageSource = new javax.swing.JLabel();
        m_label_fontFace = new javax.swing.JLabel();
        m_label_voicePersonality = new javax.swing.JLabel();
        m_label_leftClick = new javax.swing.JLabel();
        m_label_middleClick = new javax.swing.JLabel();
        m_label_rightClick = new javax.swing.JLabel();
        m_label_rightClick1 = new javax.swing.JLabel();
        m_slider_lineWidth = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        m_slider_textDepth = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Power Reader Options");
        m_combo_dictionaryLookup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Wiktionary", "WordNet Dictionary" }));

        m_combo_imageLookup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Flickr", "Google Images", "Yahoo Images" }));
        m_combo_imageLookup.setSelectedIndex(1);

        m_combo_fontFace.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tahoma" }));

        m_combo_voicePersonality.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kevin" }));
        m_combo_voicePersonality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_combo_voicePersonalityActionPerformed(evt);
            }
        });

        m_combo_leftClick.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Focus on item", "Drag and scroll", "Read dictionary definition", "Do nothing" }));

        m_combo_middleClick.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Focus on item", "Drag and scroll", "Read dictionary definition", "Do nothing" }));
        m_combo_middleClick.setSelectedIndex(2);

        m_combo_rightClick.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Focus on item", "Drag and scroll", "Read dictionary definition", "Do nothing" }));
        m_combo_rightClick.setSelectedIndex(1);

        m_okButton.setText("OK");
        m_okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_okButtonActionPerformed(evt);
            }
        });

        m_cancelButton.setText("Cancel");
        m_cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_cancelButtonActionPerformed(evt);
            }
        });

        m_checkBox_mouseWheel.setSelected(true);
        m_checkBox_mouseWheel.setText("Enable Mouse Wheel Zoom");
        m_checkBox_mouseWheel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        m_checkBox_mouseWheel.setMargin(new java.awt.Insets(0, 0, 0, 0));

        m_label_dictionarySource.setFont(new java.awt.Font("Tahoma", 1, 11));
        m_label_dictionarySource.setText("Dictionary Source");

        m_label_imageSource.setFont(new java.awt.Font("Tahoma", 1, 11));
        m_label_imageSource.setText("Image Source");

        m_label_fontFace.setFont(new java.awt.Font("Tahoma", 1, 11));
        m_label_fontFace.setText("Font Face");

        m_label_voicePersonality.setFont(new java.awt.Font("Tahoma", 1, 11));
        m_label_voicePersonality.setText("Voice Personality");

        m_label_leftClick.setFont(new java.awt.Font("Tahoma", 1, 11));
        m_label_leftClick.setText("Left Click");

        m_label_middleClick.setFont(new java.awt.Font("Tahoma", 1, 11));
        m_label_middleClick.setText("Middle Click");

        m_label_rightClick.setFont(new java.awt.Font("Tahoma", 1, 11));
        m_label_rightClick.setText("Right Click");

        m_label_rightClick1.setFont(new java.awt.Font("Tahoma", 1, 11));
        m_label_rightClick1.setText("Line Width ");
        m_label_rightClick1.setName("Line Width");

        m_slider_lineWidth.setMajorTickSpacing(10);
        m_slider_lineWidth.setMinimum(5);
        m_slider_lineWidth.setMinorTickSpacing(20);
        m_slider_lineWidth.setPaintLabels(true);
        m_slider_lineWidth.setPaintTicks(true);
        m_slider_lineWidth.setValue(20);

        jLabel1.setText("Note: Load a new file for");

        jLabel2.setText("this change to take effect");

        m_slider_textDepth.setMajorTickSpacing(1);
        m_slider_textDepth.setMaximum(10);
        m_slider_textDepth.setMinimum(1);
        m_slider_textDepth.setPaintLabels(true);
        m_slider_textDepth.setPaintTicks(true);
        m_slider_textDepth.setSnapToTicks(true);
        m_slider_textDepth.setValue(1);
        m_slider_textDepth.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                m_slider_textDepthStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Text Depth");

        jLabel4.setText("Sets the 3D Text Depth");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(m_label_fontFace)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(m_combo_fontFace, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(m_label_imageSource)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(m_combo_imageLookup, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(m_label_voicePersonality)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(m_combo_voicePersonality, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(m_label_dictionarySource)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(m_combo_dictionaryLookup, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(m_label_leftClick)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(m_combo_leftClick, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(m_label_middleClick)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(m_combo_middleClick, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(m_label_rightClick)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(m_label_rightClick1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(m_slider_textDepth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(m_checkBox_mouseWheel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(m_combo_rightClick, 0, 182, Short.MAX_VALUE))
                            .addComponent(m_slider_lineWidth, javax.swing.GroupLayout.Alignment.TRAILING, 0, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(m_okButton, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_label_dictionarySource)
                    .addComponent(m_combo_dictionaryLookup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_combo_imageLookup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_label_imageSource))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_combo_fontFace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_label_fontFace, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_combo_voicePersonality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_label_voicePersonality))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_label_leftClick)
                    .addComponent(m_combo_leftClick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_label_middleClick)
                    .addComponent(m_combo_middleClick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_combo_rightClick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_label_rightClick))
                .addGap(14, 14, 14)
                .addComponent(m_checkBox_mouseWheel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(m_label_rightClick1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(m_slider_lineWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m_slider_textDepth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_okButton)
                    .addComponent(m_cancelButton))
                .addGap(24, 24, 24))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void m_slider_textDepthStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_m_slider_textDepthStateChanged
        ConfigurationManager.TEXT_DEPTH = m_slider_textDepth.getValue() / 10.0f;
        ConfigurationManager.currentRoot.color(false);
    }//GEN-LAST:event_m_slider_textDepthStateChanged

    private void m_okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_okButtonActionPerformed
        if (m_slider_lineWidth.getValue() != (int)TextObject3d.getLineWidth()) {
            // Set the new line width
            TextObject3d.setLineWidth((float)m_slider_lineWidth.getValue());
        }
        ConfigurationManager.setDictionary(m_combo_dictionaryLookup.getSelectedIndex());
        ConfigurationManager.setImageLookup(m_combo_imageLookup.getSelectedIndex());
        ConfigurationManager.setLeftClickAction(m_combo_leftClick.getSelectedIndex());
        ConfigurationManager.setMiddleClickAction(m_combo_middleClick.getSelectedIndex());
        ConfigurationManager.setRightClickAction(m_combo_rightClick.getSelectedIndex());
        this.setVisible(false);
    }//GEN-LAST:event_m_okButtonActionPerformed

    private void m_cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_cancelButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_m_cancelButtonActionPerformed

    private void m_combo_voicePersonalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_combo_voicePersonalityActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_m_combo_voicePersonalityActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfigUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton m_cancelButton;
    private javax.swing.JCheckBox m_checkBox_mouseWheel;
    private javax.swing.JComboBox m_combo_dictionaryLookup;
    private javax.swing.JComboBox m_combo_fontFace;
    private javax.swing.JComboBox m_combo_imageLookup;
    private javax.swing.JComboBox m_combo_leftClick;
    private javax.swing.JComboBox m_combo_middleClick;
    private javax.swing.JComboBox m_combo_rightClick;
    private javax.swing.JComboBox m_combo_voicePersonality;
    private javax.swing.JLabel m_label_dictionarySource;
    private javax.swing.JLabel m_label_fontFace;
    private javax.swing.JLabel m_label_imageSource;
    private javax.swing.JLabel m_label_leftClick;
    private javax.swing.JLabel m_label_middleClick;
    private javax.swing.JLabel m_label_rightClick;
    private javax.swing.JLabel m_label_rightClick1;
    private javax.swing.JLabel m_label_voicePersonality;
    private javax.swing.JButton m_okButton;
    private javax.swing.JSlider m_slider_lineWidth;
    private javax.swing.JSlider m_slider_textDepth;
    // End of variables declaration//GEN-END:variables
    
}
